# Generated by Django 4.1.3 on 2023-04-08 07:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0005_section'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_name', models.CharField(max_length=25)),
                ('enq_date', models.DateField()),
                ('enq_followup', models.DateField()),
                ('enq_mob', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('enq_altmob', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('enq_email', models.EmailField(max_length=254)),
                ('enq_ref', models.CharField(max_length=25)),
                ('enq_det', models.TextField()),
                ('enq_active', models.BooleanField()),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('enq_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
