# Generated by Django 4.1.3 on 2023-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enq_gender',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enq_student',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
