# Generated by Django 4.1.3 on 2023-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_enquiry_enq_gender_enquiry_enq_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enq_communication',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
