# Generated by Django 4.1.3 on 2023-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_enquiry_enq_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enq_active',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enq_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
