# Generated by Django 4.1.3 on 2023-04-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_section'),
        ('institutions', '0001_initial'),
        ('admission', '0004_remove_enquiry_enq_active_enquiry_enq_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First_Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last_name')),
                ('dob_date', models.DateField()),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('admn_no', models.IntegerField()),
                ('admn_date', models.DateField()),
                ('religion', models.CharField(max_length=15, verbose_name='religion')),
                ('caste', models.CharField(max_length=50, verbose_name='caste')),
                ('blood_group', models.CharField(max_length=3, verbose_name='blood_group')),
                ('father_name', models.CharField(max_length=60, verbose_name='fname')),
                ('mother_name', models.CharField(max_length=60, verbose_name='mname')),
                ('father_occupation', models.CharField(max_length=60, verbose_name='foccup')),
                ('mother_occupation', models.CharField(max_length=60, verbose_name='moccup')),
                ('roll_no', models.CharField(max_length=6, verbose_name='rollno')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('secs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
            ],
        ),
    ]
