# Generated by Django 4.1.3 on 2023-04-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_section'),
        ('admission', '0005_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='acad_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr'),
            preserve_default=False,
        ),
    ]
