# Generated by Django 4.1.3 on 2023-04-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_students_acad_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='acad_year',
            new_name='ac_year',
        ),
    ]
