# Generated by Django 4.1.3 on 2023-04-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_section'),
        ('admission', '0007_rename_acad_year_students_ac_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ac_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr'),
        ),
    ]
