# Generated by Django 4.1.3 on 2023-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_alter_students_ac_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
