# Generated by Django 4.1.3 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_students_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
