# Generated by Django 4.1.3 on 2023-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_students_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='tc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
