# Generated by Django 4.1.3 on 2023-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_students_tc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
