# Generated by Django 4.1.3 on 2023-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='tess',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
