# Generated by Django 4.1.3 on 2023-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_students_tess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='tess',
        ),
        migrations.AddField(
            model_name='students',
            name='usernm',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
