# Generated by Django 4.1.3 on 2023-07-06 17:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_remove_students_tess_students_usernm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_altmob',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
