# Generated by Django 4.1.3 on 2023-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_alter_enquiry_enq_altmob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_altmob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_mob',
            field=models.CharField(max_length=10),
        ),
    ]
