# Generated by Django 4.1.3 on 2023-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_alter_enquiry_enq_altmob_alter_enquiry_enq_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='usernm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
