# Generated by Django 4.1.3 on 2023-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_alter_students_usernm'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
