# Generated by Django 4.1.3 on 2023-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_students_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=10, verbose_name='rollno'),
        ),
    ]
