# Generated by Django 4.2.13 on 2026-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_alter_students_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='blood_group',
            field=models.CharField(max_length=5, verbose_name='blood_group'),
        ),
    ]
