# Generated by Django 4.2.13 on 2026-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_students_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='blood_group'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
