# Generated by Django 4.1.3 on 2023-06-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0007_subjects_subject_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attndate', models.DateField()),
                ('aclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attndate', models.DateField()),
                ('student_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=13)),
                ('aclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
            ],
        ),
        migrations.CreateModel(
            name='attendancegen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attndate', models.DateField()),
                ('aclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
            ],
            options={
                'unique_together': {('aclass', 'sec', 'attndate')},
            },
        ),
    ]
