# Generated by Django 4.2.13 on 2026-07-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0011_homework_time'),
        ('institutions', '0009_schoolmenupermission'),
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_number', models.PositiveSmallIntegerField(default=1)),
                ('chapter', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('objectives', models.TextField(blank=True)),
                ('content_taught', models.TextField(blank=True)),
                ('teaching_method', models.CharField(choices=[('Lecture', 'Lecture'), ('Discussion', 'Discussion'), ('Activity', 'Activity'), ('Demo', 'Demonstration'), ('Review', 'Review'), ('Assessment', 'Assessment'), ('Group Work', 'Group Work')], default='Lecture', max_length=20)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Taught', 'Taught'), ('Skipped', 'Skipped')], default='Planned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acad_yr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'ordering': ['-date', '-period_number'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('is_given', models.BooleanField(default=False)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('corrected_date', models.DateField(blank=True, null=True)),
                ('notify_sent', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notify_success_count', models.IntegerField(default=0)),
                ('notify_total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lessonplan.lessonplan')),
            ],
        ),
    ]
