# Generated by Django 4.2.13 on 2026-07-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
        ('lessonplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('drive_file_id', models.CharField(max_length=100)),
                ('drive_view_url', models.URLField(max_length=500)),
                ('drive_download_url', models.URLField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lessonplan.lessonplan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
