# Generated by Django 4.2.13 on 2026-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='school/logo/')),
                ('founder_name', models.CharField(max_length=200)),
                ('founder_pic', models.ImageField(blank=True, null=True, upload_to='school/founder/')),
                ('founded_year', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('admission_open', models.BooleanField(default=False)),
                ('admission_url', models.URLField(blank=True)),
                ('gallery_url', models.URLField(blank=True)),
            ],
        ),
    ]
