# Generated by Django 4.2.13 on 2026-03-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_school_regno'),
        ('mobi', '0002_schoolprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
        ),
    ]
