from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('supplier/create/', login_required(views.supplier_create), name='supplier_create'),
    path('supplier/list/', login_required(views.supplier_list), name='supplier_list'),
    path('supplier/update/<int:pk>/', login_required(views.supplier_update), name='supplier_update'),
    path('supplier/delete/<int:pk>/', login_required(views.supplier_delete), name='supplier_delete'),
    path('purchase/entry/', login_required(views.purchase_entry), name='purchase_entry'),
    path('stock/list/', login_required(views.stock_list), name='stock_list'),
    path('product_update/<int:pk>/', login_required(views.product_update), name='product_update'),
    path('product_delete/<int:pk>/', login_required(views.product_delete), name='product_delete'),
    path('category/list', login_required(views.category_list), name='category_list'),
    path('category_create', login_required(views.category_create), name='category_create'),
    path('category/update/<int:pk>', login_required(views.category_update), name='category_update'),
    path('category/delete/<int:pk>', login_required(views.category_delete), name='category_delete'),
    path('product_set/create/', login_required(views.product_set_create), name='product_set_create'),
    path('product_set_list', login_required(views.product_set_list), name='product_set_list'),
    path('product_set_update/<int:pk>', login_required(views.product_set_update), name='product_set_update'),
    path('product_set_delete/<int:pk>', login_required(views.product_set_delete), name='product_set_delete'),
    path('ajax_load_class_prod', login_required(views.load_class_prod), name='ajax_load_class_prod'),
    path('reciept_book_set', login_required(views.reciept_book_set), name='reciept_book_set'),
    path('products_list', login_required(views.products_list), name='products_list'),
    path('product_create', login_required(views.product_create), name='product_create'),
    path('purchase_list', login_required(views.purchase_list), name='purchase_list'),
    path('purchase/update/<pur_id>', login_required(views.purchase_update), name='purchase_update'),
    path('purchase/delete/<pur_id>', login_required(views.purchase_delete), name='purchase_delete'),
    path('reciept_ind_book/<stud_id>', login_required(views.reciept_ind_book), name='reciept_ind_book'),
    path('set_search', login_required(views.set_search_view), name='set_search'),
    path('book_set_pdf', login_required(views.book_set_pdf), name='book_set_pdf'),
    path('stock_gen_pdf', login_required(views.stock_gen_pdf), name='stock_gen_pdf'),
    path('ind_book_pdf', login_required(views.ind_book_pdf), name='ind_book_pdf'),
    path('ajax_load_student', login_required(views.load_section), name='ajax_load_student'),
    path('book_set_rec/<stud_id>', login_required(views.book_set_rec), name='book_set_rec'),
    path('bootset_issued', login_required(views.bootset_issued), name='bootset_issued'),
    path('bookset_delete/<set_id>', login_required(views.bookset_delete), name='bookset_delete'),
    path('group_set_list', login_required(views.group_set_list), name='group_set_list'),
    path('group_set_create', login_required(views.group_set_create), name='group_set_create'),
    path('group-set/update/<int:pk>/', views.group_set_update, name='group_set_update'),
    path('group-set/delete/<int:pk>/', views.group_set_delete, name='group_set_delete'),
    path('indbook_issued', login_required(views.indbook_issued), name='indbook_issued'),
    path('indbook_delete/<ind_id>',login_required(views.indbook_delete),name='indbook_delete'),
    path('stud_search',login_required(views.stud_search),name='stud_search')
]
