# Generated by Django 4.1.3 on 2024-11-04 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0009_delete_emailsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_school_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attndate', models.DateField()),
                ('staff_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=13)),
                ('staff_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('join', models.DateField()),
                ('staff_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('role', models.CharField(max_length=150)),
                ('salary', models.FloatField()),
                ('desg', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('permission_group', models.CharField(max_length=15)),
                ('staff_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects_taught', models.ManyToManyField(blank=True, to='setup.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('homework_date', models.DateField(default=datetime.datetime.today)),
                ('description', models.CharField(max_length=250)),
                ('submission_date', models.DateField(default=datetime.datetime.today)),
                ('acad_yr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('hclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('secs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='staff_attendancegen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attndate', models.DateField()),
                ('staff_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'unique_together': {('attndate', 'staff_school')},
            },
        ),
    ]
