# Generated by Django 4.1.3 on 2023-06-19 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_subjects_subject_year'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='secs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 5, 22, 15, 15985, tzinfo=datetime.timezone.utc)),
        ),
    ]
