# Generated by Django 5.2.1 on 2025-08-02 09:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('setup', '0010_receipt_template'),
        ('staff', '0002_alter_homework_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('homework_date', models.DateField(default=datetime.datetime.today)),
                ('description', models.CharField(max_length=180)),
                ('submission_date', models.DateField(default=datetime.datetime.today)),
                ('acad_yr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('hclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('secs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subjects')),
            ],
        ),
    ]
