# Generated by Django 4.1.3 on 2023-06-19 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_homework_secs_alter_homework_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 5, 22, 43, 344506, tzinfo=datetime.timezone.utc)),
        ),
    ]
