# Generated by Django 5.2.1 on 2025-08-16 07:08

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_temp_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/'),
        ),
        migrations.AddField(
            model_name='temp_homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=staff.models.homework_upload_path),
        ),
    ]
