# Generated by Django 4.1.3 on 2023-06-19 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('staff', '0003_alter_homework_homework_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='school_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 6, 21, 37, 382138, tzinfo=datetime.timezone.utc)),
        ),
    ]
