# Generated by Django 4.2.13 on 2026-02-25 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('staff', '0004_homework_attachment_temp_homework_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='BioCode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='EmpCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(default='Basic_shift', max_length=50)),
                ('start_time', models.TimeField(default=datetime.time(8, 35))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.dept'),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.shift'),
        ),
    ]
