# Generated by Django 4.1.3 on 2023-06-19 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_homework_school_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 6, 29, 59, 156525, tzinfo=datetime.timezone.utc)),
        ),
    ]
