# Generated by Django 4.1.3 on 2023-06-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_homework_homework_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='sclass',
            new_name='hclass',
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 6, 38, 58, 269338, tzinfo=datetime.timezone.utc)),
        ),
    ]
