# Generated by Django 4.2.13 on 2026-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_biocode_staff_empcode_shift_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Probation', 'Probation')], default='Permanent', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
