# Generated by Django 4.1.3 on 2023-06-19 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_sclass_homework_hclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='students',
            new_name='stud',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='subject',
            new_name='subj',
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 7, 3, 23, 566927, tzinfo=datetime.timezone.utc)),
        ),
    ]
