# Generated by Django 4.1.3 on 2023-06-19 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_rename_students_homework_stud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 7, 37, 2, 771631, tzinfo=datetime.timezone.utc)),
        ),
    ]
