# Generated by Django 4.1.3 on 2023-06-19 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_homework_homework_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
