# Generated by Django 4.1.3 on 2023-06-19 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_subjects_subject_year'),
        ('staff', '0010_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='acad_yr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 14, 31, 52, 528091)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 14, 31, 52, 528091)),
        ),
    ]
