# Generated by Django 4.1.3 on 2023-06-20 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 14, 45, 55, 28259)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 14, 45, 55, 28259)),
        ),
    ]
