# Generated by Django 4.1.3 on 2023-06-28 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 15, 55, 50, 112151)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 15, 55, 50, 112151)),
        ),
    ]
