# Generated by Django 4.1.3 on 2023-07-03 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0053_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 11, 41, 4, 576697)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 11, 41, 4, 576697)),
        ),
    ]
