# Generated by Django 4.1.3 on 2023-07-06 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0074_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 22, 59, 2, 96107)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 22, 59, 2, 96107)),
        ),
    ]
