# Generated by Django 4.1.3 on 2023-07-07 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0075_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 10, 9, 22, 173614)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 10, 9, 22, 173614)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
