# Generated by Django 4.1.3 on 2023-07-07 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0077_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 43, 47, 649581)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 43, 47, 649581)),
        ),
    ]
