# Generated by Django 4.1.3 on 2023-07-08 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0082_alter_homework_homework_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='stud',
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 14, 12, 46, 369116)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 14, 12, 46, 369116)),
        ),
    ]
