# Generated by Django 4.1.3 on 2024-02-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VTitle', models.CharField(max_length=80)),
                ('Vdesc', models.CharField(max_length=255)),
                ('Vdate', models.DateField()),
                ('Vpostdate', models.DateField()),
                ('Vlink', models.CharField(max_length=255)),
                ('VThumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('status', models.CharField(max_length=9)),
                ('Vschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
