# Generated by Django 4.1.3 on 2023-04-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='addindfee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession', models.IntegerField()),
                ('invoice_no', models.IntegerField()),
                ('status', models.CharField(max_length=6)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=250)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fee_amount', models.IntegerField()),
                ('latefee', models.IntegerField()),
                ('isactive', models.CharField(max_length=3)),
                ('ac_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('fees_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('iclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
            ],
        ),
        migrations.CreateModel(
            name='fee_reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_date', models.DateField()),
                ('reciept_no', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('paid_amt', models.IntegerField(blank=True, null=True)),
                ('reciept_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.addindfee')),
            ],
        ),
        migrations.CreateModel(
            name='bulkfee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('fee_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees')),
            ],
        ),
        migrations.AddField(
            model_name='addindfee',
            name='fee_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees'),
        ),
        migrations.AddField(
            model_name='addindfee',
            name='stud_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students'),
        ),
    ]
