# Generated by Django 4.1.3 on 2023-04-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fees_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='invoice_no',
        ),
    ]
