# Generated by Django 4.1.3 on 2023-04-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_subjects'),
        ('fees', '0003_remove_fees_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='ac_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr'),
        ),
    ]
