# Generated by Django 4.1.3 on 2023-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_fees_ac_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_reciept',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fee_reciept',
            name='payment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
