# Generated by Django 4.1.3 on 2023-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_fee_reciept_note_fee_reciept_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addindfee',
            name='paid_amt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
