# Generated by Django 4.1.3 on 2023-05-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_addindfee_paid_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addindfee',
            old_name='paid_amt',
            new_name='due_amt',
        ),
    ]
