# Generated by Django 4.1.3 on 2023-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_rename_paid_amt_addindfee_due_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addindfee',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
