# Generated by Django 4.1.3 on 2023-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_addindfee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='fee_group',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
