# Generated by Django 4.1.3 on 2025-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_fees_fee_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='addindfee',
            name='concession_apply',
            field=models.BooleanField(default=False),
        ),
    ]
