# Generated by Django 4.1.3 on 2025-04-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_delete_emailsettings'),
        ('fees', '0010_addindfee_concession_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkfee',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr'),
        ),
    ]
