# Generated by Django 4.1.3 on 2025-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_alter_students_roll_no'),
        ('fees', '0011_bulkfee_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addindfee',
            name='stud_name',
        ),
        migrations.AddField(
            model_name='addindfee',
            name='stud_name',
            field=models.ManyToManyField(to='admission.students'),
        ),
    ]
