# Generated by Django 4.1.3 on 2025-04-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_alter_students_roll_no'),
        ('fees', '0012_remove_addindfee_stud_name_addindfee_stud_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addindfee',
            name='stud_name',
        ),
        migrations.AddField(
            model_name='addindfee',
            name='stud_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.students'),
        ),
    ]
