# Generated by Django 4.2.13 on 2026-05-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_alter_students_blood_group_alter_students_email'),
        ('fees', '0013_remove_addindfee_stud_name_addindfee_stud_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayUTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='initiated', max_length=20)),
                ('payu_txnid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fees.addindfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
        ),
    ]
