# Generated by Django 4.2.13 on 2026-05-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_school_regno'),
        ('fees', '0014_payutransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPayUConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=100)),
                ('merchant_salt', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payu_config', to='institutions.school')),
            ],
        ),
    ]
