# Generated by Django 4.2.13 on 2026-05-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_alter_students_blood_group_alter_students_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0008_alter_school_regno'),
        ('fees', '0015_schoolpayuconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='del_fee_reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_date', models.DateField()),
                ('deletedate', models.DateField()),
                ('reciept_no', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('reciept_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.addindfee')),
                ('reciept_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
