# Generated by Django 4.1.3 on 2024-12-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0020_alter_students_roll_no'),
        ('institutions', '0003_school_website'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=12)),
                ('success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('Notification_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_school', to='institutions.school')),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to='staff.staff')),
                ('post_to', models.ManyToManyField(related_name='notifications_received', to='admission.students')),
            ],
        ),
    ]
