# Generated by Django 5.2.1 on 2025-06-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('pushnotify', '0001_initial'),
        ('setup', '0010_receipt_template'),
        ('staff', '0002_alter_homework_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_msg', models.CharField(max_length=50)),
                ('message_cont', models.CharField(max_length=155)),
                ('create_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('status', models.CharField(max_length=12)),
                ('success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('Notification_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SectionwiseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_msg', models.CharField(max_length=50)),
                ('message_cont', models.CharField(max_length=155)),
                ('create_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('status', models.CharField(max_length=12)),
                ('success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('Notification_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('aclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('ssec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
            ],
        ),
    ]
