# Generated by Django 5.2.1 on 2025-06-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_alter_students_roll_no'),
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('pushnotify', '0002_schoolnotification_sectionwisenotification'),
        ('staff', '0002_alter_homework_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_GeneralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=12)),
                ('success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('Notification_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('post_to', models.ManyToManyField(to='admission.students')),
            ],
        ),
    ]
