# Generated by Django 4.2.13 on 2026-06-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_school_regno'),
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
        ('pushnotify', '0003_temp_generalnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('status', models.CharField(max_length=12)),
                ('success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('Notification_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notification_school', to='institutions.school')),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff_notifications', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='pushnotify.staffnotification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to='staff.staff')),
            ],
            options={
                'unique_together': {('notification', 'staff')},
            },
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='post_to',
            field=models.ManyToManyField(through='pushnotify.StaffNotificationRecipient', to='staff.staff'),
        ),
    ]
