# Generated by Django 4.2.13 on 2026-06-30 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0008_alter_school_regno'),
        ('admission', '0022_alter_students_blood_group_alter_students_email'),
        ('setup', '0011_homework_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=15)),
            ],
            options={
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('warden', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveSmallIntegerField(default=0)),
                ('floor_name', models.CharField(blank=True, max_length=40, null=True)),
                ('total_rooms', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_set', to='hostel.block')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('block', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-ed', 'Co-ed'), ('Staff', 'Staff')], default='Boys', max_length=10)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('campus', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('warden', models.CharField(blank=True, max_length=80, null=True)),
                ('warden_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('vacate_date', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('parent_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Vacated', 'Vacated'), ('Transferred', 'Transferred')], default='Active', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ac_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.bed')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.block')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.floor')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid'), ('Waived', 'Waived')], default='Pending', max_length=10)),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hostel.hosteladmission')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Dormitory', 'Dormitory'), ('AC', 'AC Room'), ('Non-AC', 'Non-AC Room')], max_length=20, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=15)),
                ('requested_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
            options={
                'ordering': ['priority', 'requested_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.bed')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.bed')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Dormitory', 'Dormitory'), ('AC', 'AC Room'), ('Non-AC', 'Non-AC Room')], default='Double', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=15)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.block')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.floor')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_away', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='HostelFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_period', models.CharField(choices=[('One-time', 'One-time'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Annual', 'Annual')], default='Monthly', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='hostel.hostel')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelFeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20)),
                ('receipt_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('DD', 'Demand Draft'), ('UPI', 'UPI')], default='Cash', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='hostel.hostelfeeinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.AddField(
            model_name='hostelfeeinvoice',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelfeetype'),
        ),
        migrations.AddField(
            model_name='hostelfeeinvoice',
            name='sch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
        ),
        migrations.AddField(
            model_name='hostelfeeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students'),
        ),
        migrations.AddField(
            model_name='hosteladmission',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room'),
        ),
        migrations.AddField(
            model_name='hosteladmission',
            name='sch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
        ),
        migrations.AddField(
            model_name='hosteladmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students'),
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(max_length=20)),
                ('out_datetime', models.DateTimeField()),
                ('expected_return', models.DateTimeField()),
                ('actual_return', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Open', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
            options={
                'ordering': ['-out_datetime'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room'),
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('Morning', 'Morning Roll Call'), ('Evening', 'Evening Roll Call'), ('Night', 'Night Roll Call')], default='Night', max_length=10)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'On Leave'), ('Out', 'Out Pass')], default='Present', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
            options={
                'ordering': ['student__first_name'],
                'unique_together': {('student', 'date', 'session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
