# Generated by Django 4.2.21 on 2026-02-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0011_homework_time'),
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('admission', '0020_alter_students_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='phone')),
                ('area_of_complaint', models.CharField(choices=[('Academic', 'Academic'), ('Non-Academic', 'Non-Academic'), ('Activities', 'Activities'), ('Transport', 'Transport'), ('Office', 'Office'), ('Other', 'Other')], max_length=20)),
                ('aoc_other', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.TextField(max_length=250)),
                ('principal_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('concern_person_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('act_details', models.CharField(blank=True, max_length=100, null=True)),
                ('act_intimation_to_person', models.CharField(choices=[('Oral', 'Oral'), ('Phone', 'Phone'), ('In-Person', 'In-Person'), ('Email', 'Email'), ('Whatsapp', 'Whatsapp'), ('APP', 'APP')], max_length=20)),
                ('complaint_date', models.DateTimeField()),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('complaint_status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Resolved', 'Resolved')], max_length=20)),
                ('complaint_received', models.CharField(choices=[('Oral', 'Oral'), ('Phone', 'Phone'), ('In-Person', 'In-Person'), ('Email', 'Email'), ('Whatsapp', 'Whatsapp'), ('APP', 'APP')], max_length=20)),
                ('concern_person_name', models.CharField(default='Anonymous', max_length=150)),
                ('no_action_taken', models.BooleanField(default=True)),
                ('ac_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
                ('gclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.sclass')),
                ('gschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('gsec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.section')),
                ('stud_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.students')),
            ],
        ),
    ]
