# Generated by Django 4.1.3 on 2023-06-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('setup', '0007_subjects_subject_year'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admit_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='temp_insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_prefix', models.CharField(max_length=5)),
                ('exam_start_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=50)),
                ('exam_code', models.CharField(max_length=50)),
                ('exam_centre', models.CharField(max_length=50)),
                ('exam_Sub_count', models.IntegerField()),
                ('exam_groupby', models.CharField(max_length=25)),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('exam_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
            ],
        ),
        migrations.CreateModel(
            name='exam_subjectmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_subject_type', models.CharField(max_length=15)),
                ('paper_code', models.CharField(max_length=10)),
                ('paper_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(max_length=10)),
                ('max_marks', models.IntegerField()),
                ('exam_subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subjects')),
                ('exname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exams')),
            ],
        ),
        migrations.CreateModel(
            name='exam_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('adm_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.admit_card')),
                ('exam_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exam_subjectmap')),
            ],
        ),
        migrations.AddField(
            model_name='admit_card',
            name='exam_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.exams'),
        ),
        migrations.AddField(
            model_name='admit_card',
            name='exam_stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students'),
        ),
    ]
