# Generated by Django 4.1.3 on 2023-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='published',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='remark',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
