# Generated by Django 4.1.3 on 2024-01-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_exams_published_exams_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm_group', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='exm_grp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.exam_group'),
        ),
    ]
