# Generated by Django 4.1.3 on 2024-01-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_school_logo'),
        ('examination', '0003_exam_group_exams_exm_grp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_group',
            name='exam_group_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
            preserve_default=False,
        ),
    ]
