# Generated by Django 4.1.3 on 2024-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_exam_group_exam_group_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='remark',
            field=models.CharField(max_length=6),
        ),
    ]
