# Generated by Django 4.1.3 on 2024-05-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_school_logo'),
        ('examination', '0005_alter_exams_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_group',
            name='exam_group_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.school'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_groupby',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
