# Generated by Django 4.1.3 on 2024-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_alter_exams_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='exam_groupby',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
