# Generated by Django 4.1.3 on 2024-07-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_alter_exam_group_exam_group_school_and_more'),
        ('examination', '0007_alter_exam_group_exam_group_school'),
    ]

    operations = [
    ]
