# Generated by Django 5.2.1 on 2025-08-04 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomateFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('task', models.CharField(choices=[('fee_collection', 'Fee Collection'), ('petty_cash', 'Petty Cash'), ('stocks', 'Stocks'), ('summarys', 'Summary')], max_length=40)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=100)),
                ('schedule_time', models.TimeField()),
                ('automate_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('send_to', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'verbose_name': 'Automated Task',
                'verbose_name_plural': 'Automated Tasks',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='fee_automate_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=40)),
                ('reporter_name', models.CharField(max_length=75)),
                ('report_to', models.CharField(max_length=15)),
                ('report_create_date', models.DateTimeField()),
                ('report_status', models.CharField(max_length=10)),
                ('report_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
