# Generated by Django 4.2.21 on 2025-12-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatefunc',
            name='task',
            field=models.CharField(choices=[('fee_collection', 'Fee Collection'), ('petty_cash', 'Petty Cash'), ('stocks', 'Stocks'), ('summarys', 'Summary'), ('Grievance', 'Grievance')], max_length=40),
        ),
    ]
