# Generated by Django 4.2.21 on 2025-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0003_alter_automatefunc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatefunc',
            name='task',
            field=models.CharField(choices=[('fee_collection', 'Fee Collection'), ('petty_cash', 'Petty Cash'), ('stocks', 'Stocks'), ('summarys', 'Summary'), ('Grievance_Report', 'Grievance_Report'), ('Grievance_over_Due', 'Grievance_over_Due')], max_length=40),
        ),
    ]
