# Generated by Django 4.1.3 on 2023-04-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acad_year', models.CharField(max_length=10)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
