# Generated by Django 4.1.3 on 2023-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentacademicyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.academicyr')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
