# Generated by Django 4.1.3 on 2023-04-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('setup', '0002_currentacademicyr'),
    ]

    operations = [
        migrations.CreateModel(
            name='sclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_nam', to='institutions.school')),
            ],
        ),
    ]
