# Generated by Django 4.1.3 on 2023-04-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_sclass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sclass',
            unique_together={('name', 'acad_year')},
        ),
    ]
