# Generated by Django 4.1.3 on 2023-04-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('setup', '0004_alter_sclass_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.currentacademicyr')),
                ('class_sec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_school_name', to='institutions.school')),
            ],
        ),
    ]
