# Generated by Django 4.1.3 on 2023-04-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr'),
            preserve_default=False,
        ),
    ]
