# Generated by Django 4.1.3 on 2023-06-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('setup', '0007_subjects_subject_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('host_user', models.EmailField(max_length=254)),
                ('host_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField()),
                ('email_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
