# Generated by Django 4.1.3 on 2023-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_emailsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
