# Generated by Django 4.1.3 on 2025-05-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('setup', '0009_delete_emailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=50)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
