# Generated by Django 4.1.3 on 2024-10-29 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_school_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notice_date', models.DateField(default=datetime.datetime.today)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_files/')),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(max_length=10)),
                ('notice_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_desc', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('post_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(max_length=200)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
