# Generated by Django 4.1.3 on 2023-06-20 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notice_date', models.DateField(default=datetime.datetime(2023, 6, 20, 10, 42, 27, 439596))),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_files/')),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(max_length=10)),
                ('notice_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
