# Generated by Django 4.1.3 on 2023-06-20 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/notice_files/'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 11, 28, 14, 133431)),
        ),
    ]
