# Generated by Django 4.1.3 on 2023-06-20 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_noticeboard_file_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice_files/'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 14, 45, 55, 39688)),
        ),
    ]
