# Generated by Django 4.1.3 on 2023-06-20 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('academic', '0004_alter_noticeboard_notice_date_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 15, 33, 20, 271985)),
        ),
    ]
