# Generated by Django 4.1.3 on 2023-06-20 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_rename_event_events_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 18, 37, 56, 36835)),
        ),
    ]
