# Generated by Django 4.1.3 on 2023-06-25 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_events_end_date_alter_events_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 22, 16, 8, 555065)),
        ),
    ]
