# Generated by Django 4.1.3 on 2023-06-30 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 15, 21, 2, 266714)),
        ),
    ]
