# Generated by Django 4.1.3 on 2023-07-03 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 16, 17, 22, 609411)),
        ),
    ]
