# Generated by Django 4.1.3 on 2023-07-05 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0055_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 22, 13, 5, 159001)),
        ),
    ]
