# Generated by Django 4.1.3 on 2023-07-07 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0064_alter_noticeboard_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 21, 28, 59, 747818)),
        ),
    ]
