# Generated by Django 4.1.3 on 2023-09-18 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_school_logo'),
        ('setup', '0009_delete_emailsettings'),
        ('admission', '0019_students_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cat_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='group_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
                ('group_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_number2', models.CharField(max_length=20)),
                ('Sup_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('Prod_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('invoice_no', models.IntegerField()),
                ('order_dt', models.DateField()),
                ('rec_dt', models.DateField()),
                ('Prod_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='product_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('ac_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group_set')),
                ('pclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('prod_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ind_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime(2023, 9, 18, 7, 24, 51, 668553))),
                ('isbook_set', models.CharField(max_length=5)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('bclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('ind_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('inv_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
        ),
        migrations.CreateModel(
            name='book_set_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime(2023, 9, 18, 7, 24, 51, 630478))),
                ('status', models.CharField(max_length=10)),
                ('book_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group_set')),
                ('book_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
                ('set_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('stud_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
            ],
        ),
    ]
