# Generated by Django 4.1.3 on 2024-10-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
