# Generated by Django 4.2.21 on 2025-11-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_set',
            name='prod_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products'),
        ),
    ]
