# Generated by Django 4.1.3 on 2023-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_name_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_set_issue',
            name='status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
