# Generated by Django 4.1.3 on 2023-07-03 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_remove_students_tess_students_usernm'),
        ('institutions', '0001_initial'),
        ('inventory', '0004_book_set_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 18, 26, 39, 813789)),
        ),
        migrations.AddField(
            model_name='book_set_issue',
            name='set_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ind_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime(2023, 7, 3, 18, 26, 39, 814790))),
                ('isbook_set', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('inv_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
        ),
    ]
