# Generated by Django 4.1.3 on 2023-07-03 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('inventory', '0005_book_set_issue_issue_date_book_set_issue_set_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_book',
            name='ind_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 19, 42, 31, 414449)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 19, 42, 31, 414449)),
        ),
    ]
