# Generated by Django 4.1.3 on 2023-07-03 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_delete_emailsettings'),
        ('inventory', '0007_alter_book_set_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_book',
            name='bclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.sclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 21, 45, 9, 193634)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 21, 45, 9, 193634)),
        ),
    ]
