# Generated by Django 4.1.3 on 2023-07-03 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_ind_book_bclass_alter_book_set_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_book',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 22, 40, 27, 523204)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 22, 40, 27, 523204)),
        ),
    ]
