# Generated by Django 4.1.3 on 2023-07-06 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_book_set_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 22, 52, 55, 493326)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 22, 52, 55, 493326)),
        ),
    ]
