# Generated by Django 4.1.3 on 2023-07-07 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_delete_emailsettings'),
        ('inventory', '0018_alter_book_set_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_set',
            name='ac_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.academicyr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 26, 19, 713960)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 26, 19, 713960)),
        ),
    ]
