# Generated by Django 4.1.3 on 2023-07-07 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_set_ac_year_alter_book_set_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_set_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 43, 47, 658593)),
        ),
        migrations.AlterField(
            model_name='ind_book',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 18, 43, 47, 658593)),
        ),
    ]
