# Generated by Django 4.2.13 on 2026-05-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('report_submitted_by', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('total_strength', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('boys', models.PositiveIntegerField(default=0)),
                ('girls', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='jacobreports.classteacherreport')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='jacobreports.classteacherreport')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionGrievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='jacobreports.classteacherreport')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_for', models.CharField(choices=[('parents', 'Parents'), ('pupils', 'Pupils')], max_length=20)),
                ('description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='jacobreports.classteacherreport')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boys', models.PositiveIntegerField()),
                ('girls', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength', to='jacobreports.classteacherreport')),
            ],
        ),
    ]
