# Generated by Django 4.2.13 on 2026-05-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_homework_time'),
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
        ('institutions', '0008_alter_school_regno'),
        ('jacobreports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalremark',
            name='report',
        ),
        migrations.RemoveField(
            model_name='suggestiongrievance',
            name='report',
        ),
        migrations.RemoveField(
            model_name='teachermeeting',
            name='report',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='report',
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='accident_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='activity_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='announcements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='birthday_celebration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='boys_absentees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='boys_on_roll',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='boys_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='boys_uniform_defaulters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='bus_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='bus_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='cycle_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='cycle_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='defaulters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='drill_work_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='girls_absentees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='girls_on_roll',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='girls_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='girls_uniform_defaulters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='homework_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='meeting_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='others_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='others_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='parents_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='private_auto_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='private_auto_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='pupils_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='school_van_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='school_van_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='suggestions_and_grievances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='teachers_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='walk_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='walk_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classteacherreport',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass'),
        ),
        migrations.AlterField(
            model_name='classteacherreport',
            name='report_submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='classteacherreport',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
        ),
        migrations.AlterField(
            model_name='classteacherreport',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacherreport',
            unique_together={('class_name', 'section', 'report_date')},
        ),
        migrations.DeleteModel(
            name='ClassStrength',
        ),
        migrations.DeleteModel(
            name='GeneralRemark',
        ),
        migrations.DeleteModel(
            name='SuggestionGrievance',
        ),
        migrations.DeleteModel(
            name='TeacherMeeting',
        ),
        migrations.DeleteModel(
            name='TransportDetail',
        ),
        migrations.RemoveField(
            model_name='classteacherreport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='classteacherreport',
            name='total_strength',
        ),
    ]
