# Generated by Django 4.2.13 on 2026-07-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_school_regno'),
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
        ('jacobreports', '0002_remove_generalremark_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InchargeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_time', models.TimeField()),
                ('report_date', models.DateField()),
                ('department', models.CharField(choices=[('Primary', 'Primary'), ('Middle School', 'Middle School'), ('High School', 'High School'), ('Higher Secondary', 'Higher Secondary')], max_length=50)),
                ('late_comers_teachers', models.TextField(blank=True, null=True)),
                ('late_comers_duty_teachers', models.TextField(blank=True, null=True)),
                ('absentees_teachers', models.TextField(blank=True, null=True)),
                ('zero_hour_maintained', models.BooleanField(default=False)),
                ('assembly_arrangements', models.TextField(blank=True, null=True)),
                ('class_teachers_morals', models.CharField(choices=[('Given', 'Given'), ('Not Given', 'Not Given')], default='Given', max_length=20)),
                ('dispersing_time', models.TimeField(blank=True, null=True)),
                ('ct_availability', models.BooleanField(default=True)),
                ('children_without_lunch', models.PositiveIntegerField(default=0)),
                ('lunch_atmosphere', models.CharField(choices=[('Calm', 'Calm'), ('Noisy', 'Noisy')], default='Calm', max_length=10)),
                ('noise_level', models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=10, null=True)),
                ('cram_conducted', models.TextField(blank=True, null=True)),
                ('special_class', models.TextField(blank=True, null=True)),
                ('activity_class', models.TextField(blank=True, null=True)),
                ('accident_details', models.TextField(blank=True, null=True)),
                ('incidents', models.TextField(blank=True, null=True)),
                ('pupils_detained', models.TextField(blank=True, null=True)),
                ('class_work_given', models.BooleanField(default=False)),
                ('homework_corrected', models.BooleanField(default=False)),
                ('handbook_checked', models.BooleanField(default=False)),
                ('supervising_report', models.TextField(blank=True, null=True)),
                ('period_1', models.TextField(blank=True, null=True)),
                ('period_2', models.TextField(blank=True, null=True)),
                ('period_3', models.TextField(blank=True, null=True)),
                ('period_4', models.TextField(blank=True, null=True)),
                ('period_5', models.TextField(blank=True, null=True)),
                ('period_6', models.TextField(blank=True, null=True)),
                ('period_7', models.TextField(blank=True, null=True)),
                ('period_8', models.TextField(blank=True, null=True)),
                ('circular_teachers', models.TextField(blank=True, null=True)),
                ('circular_parents', models.TextField(blank=True, null=True)),
                ('circular_pupils', models.TextField(blank=True, null=True)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('competition_field_trip', models.TextField(blank=True, null=True)),
                ('celebration', models.TextField(blank=True, null=True)),
                ('meeting_conducted', models.TextField(blank=True, null=True)),
                ('meeting_details', models.TextField(blank=True, null=True)),
                ('demo_class', models.TextField(blank=True, null=True)),
                ('rounds_report', models.TextField(blank=True, null=True)),
                ('staff_prayer_attendance', models.TextField(blank=True, null=True)),
                ('suggestions_and_grievances', models.TextField(blank=True, null=True)),
                ('late_evening_class_std', models.CharField(blank=True, max_length=50, null=True)),
                ('late_evening_class_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('late_evening_class_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('late_evening_class_students', models.PositiveIntegerField(default=0)),
                ('tomorrows_assignment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'ordering': ['-report_date', '-id'],
                'unique_together': {('school_name', 'department', 'report_date')},
            },
        ),
    ]
