# Generated by Django 5.2.17 on 2026-09-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_groupmenupermission_school_wise'),
        ('jacobreports', '0008_add_incharge_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('Todays Schedule', "Today's Schedule"), ('Observ & Compl', 'Observations & Complaints'), ('Sugg & Griev', 'Suggestions & Grievances'), ('Activities', 'Activities'), ('Followup', 'Follow Up'), ('Meeting Agenda', 'Meeting Agenda'), ('Incidents & Accidents', 'Incidents & Accidents'), ('Resolution', 'Resolution')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Issue', 'Issue')], default='Closed', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'ordering': ['-entry_date', 'entry_type', 'id'],
            },
        ),
    ]
