# Generated by Django 5.2.17 on 2026-09-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_groupmenupermission_school_wise'),
        ('jacobreports', '0009_principaldailylog'),
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalLogAccessMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_log_access', to='staff.staff')),
            ],
            options={
                'unique_together': {('school_name', 'staff_member')},
            },
        ),
    ]
