# Generated by Django 5.2.17 on 2026-09-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_groupmenupermission_school_wise'),
        ('jacobreports', '0010_principallogaccessmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principaldailylog',
            name='entry_type',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='PrincipalLogEntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school_name', 'name')},
            },
        ),
    ]
