# Generated by Django 4.2.13 on 2026-02-25 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('staff', '0005_staff_biocode_staff_empcode_shift_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allow_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('percentage_basic', 'Percentage of Basic Salary'), ('percentage_gross', 'Percentage of Gross Salary'), ('fixed_amount', 'Fixed Monthly Amount'), ('emi', 'EMI Based Deduction')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed', max_digits=10)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=datetime.date(2900, 1, 1))),
                ('ciel_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min salary to apply this deduction', max_digits=10, null=True)),
                ('ciel_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max salary to apply this deduction', max_digits=10, null=True)),
                ('ciel_based_on', models.CharField(blank=True, choices=[('basic', 'Basic Salary'), ('gross', 'Gross Salary')], help_text='Check ceiling based on Basic/Gross salary', max_length=10, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('hra_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('wages_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='tempattend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.PositiveIntegerField(default=5)),
                ('payroll_month_cycle', models.CharField(choices=[('JAN-DEC', 'JAN - DEC'), ('JUN-MAY', 'JUN - MAY'), ('APR-MAR', 'APR - MAR')], default='JUN-MAY', max_length=20)),
                ('total_cl', models.PositiveIntegerField(default=12)),
                ('cl_per_month', models.PositiveIntegerField(default=1)),
                ('allow_previous_cl_usage', models.BooleanField(default=True)),
                ('total_ml', models.PositiveIntegerField(default=3)),
                ('grace_late_count', models.PositiveIntegerField(default=3)),
                ('lop_after_grace', models.DecimalField(decimal_places=2, default=0.25, max_digits=4)),
                ('late_cutoff_hour', models.PositiveIntegerField(default=9)),
                ('permission_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('permission_per_month', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccNo', models.CharField(max_length=25)),
                ('CIFNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BankName', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=25)),
                ('IFSC', models.CharField(max_length=10)),
                ('CustName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_deduction_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deduction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_allowance_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_lop_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cl_balance', models.DecimalField(decimal_places=1, default=12, max_digits=4)),
                ('ml_balance', models.DecimalField(decimal_places=1, default=10, max_digits=4)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'unique_together': {('staff', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(choices=[('Weekly-OFF', 'Weekly-OFF'), ('Special-OFF', 'Special-OFF')], max_length=20)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'unique_together': {('sch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('punch_count', models.IntegerField(default=0)),
                ('work_duration', models.DurationField(blank=True, null=True)),
                ('late_minutes', models.IntegerField(default=0)),
                ('late', models.BooleanField(default=False)),
                ('mis_punch', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('MIS_PUNCH', 'Miss Punch'), ('CL', 'Casual Leave'), ('ML', 'Medical Leave'), ('PERMISSION', 'Permission'), ('LOP', 'Loss of Pay'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('leave_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='payroll_att_date_6e9150_idx'), models.Index(fields=['staff'], name='payroll_att_staff_i_2c1f7b_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
