# Generated by Django 4.2.21 on 2026-02-09 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allow_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('percentage_basic', 'Percentage of Basic Salary'), ('percentage_gross', 'Percentage of Gross Salary'), ('fixed_amount', 'Fixed Monthly Amount'), ('emi', 'EMI Based Deduction')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed', max_digits=10)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=datetime.date(2900, 1, 1))),
                ('ciel_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min salary to apply this deduction', max_digits=10, null=True)),
                ('ciel_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max salary to apply this deduction', max_digits=10, null=True)),
                ('ciel_based_on', models.CharField(blank=True, choices=[('basic', 'Basic Salary'), ('gross', 'Gross Salary')], help_text='Check ceiling based on Basic/Gross salary', max_length=10, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.designation')),
                ('emp_sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='tempattend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccNo', models.CharField(max_length=25)),
                ('CIFNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BankName', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=25)),
                ('IFSC', models.CharField(max_length=10)),
                ('CustName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_deduction_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deduction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_allowance_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
    ]
