# Generated by Django 4.2.13 on 2026-02-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('pf_basic_limit', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=3.25, max_digits=5)),
                ('esi_gross_limit', models.DecimalField(decimal_places=2, default=21000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
    ]
