# Generated by Django 4.2.21 on 2026-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='EmpType',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
    ]
