# Generated by Django 4.2.13 on 2026-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_statutorysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='basic_da',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollmonthly',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
