# Generated by Django 4.2.21 on 2026-02-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollemployee_emptype_delete_employeetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='EmpType',
            new_name='emp_type',
        ),
    ]
