# Generated by Django 4.2.13 on 2026-02-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollmonthly_basic_da_payrollmonthly_hra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollmonthly',
            name='salary_days',
        ),
        migrations.RemoveField(
            model_name='payrollmonthly',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='payrollmonthly',
            name='working_days',
        ),
    ]
