# Generated by Django 4.2.21 on 2026-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_rename_emptype_payrollemployee_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollemployee',
            name='emp_type',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
