# Generated by Django 4.2.13 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payrollmonthly_salary_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
