# Generated by Django 4.2.13 on 2026-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollmonthly_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollmonthly',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
