# Generated by Django 4.2.13 on 2026-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollmonthly_esi_payrollmonthly_pf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='total_sal_month',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
