# Generated by Django 4.2.13 on 2026-02-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_biocode_staff_empcode_shift_dept_and_more'),
        ('payroll', '0007_payrollmonthly_total_sal_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
