# Generated by Django 4.2.13 on 2026-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_loan_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='ded',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
