# Generated by Django 4.2.13 on 2026-02-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payrollmonthly_ded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
