# Generated by Django 4.2.13 on 2026-02-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_staff_type_alter_staff_salary'),
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('payroll', '0010_delete_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='staff_deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.deductions')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_deduction_details',
            name='deduction_name',
        ),
        migrations.RemoveField(
            model_name='employee_deduction_details',
            name='employee_name',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='Employee_deduction_Details',
        ),
    ]
