# Generated by Django 4.2.13 on 2026-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_deductions_staff_deduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_deduction',
            name='balance',
        ),
        migrations.AddField(
            model_name='payrollmonthly',
            name='total_ded',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
