# Generated by Django 4.2.13 on 2026-03-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_school_group_code'),
        ('payroll', '0012_remove_staff_deduction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollbank',
            name='home_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.school'),
            preserve_default=False,
        ),
    ]
