# Generated by Django 4.2.13 on 2026-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_payrollbank_home_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbank',
            name='BankName',
            field=models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('Punjab National Bank', 'Punjab National Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Indian Bank', 'Indian Bank'), ('Bank of India', 'Bank of India'), ('Central Bank of India', 'Central Bank of India'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('UCO Bank', 'UCO Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Punjab & Sind Bank', 'Punjab & Sind Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Axis Bank', 'Axis Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('Federal Bank', 'Federal Bank'), ('RBL Bank', 'RBL Bank'), ('Bandhan Bank', 'Bandhan Bank'), ('South Indian Bank', 'South Indian Bank'), ('Yes Bank', 'Yes Bank'), ('AU Small Finance Bank', 'AU Small Finance Bank'), ('Ujjivan Small Finance Bank', 'Ujjivan Small Finance Bank'), ('Equitas Small Finance Bank', 'Equitas Small Finance Bank'), ('ESAF Small Finance Bank', 'ESAF Small Finance Bank'), ('Suryoday Small Finance Bank', 'Suryoday Small Finance Bank'), ('India Post Payments Bank', 'India Post Payments Bank'), ('Airtel Payments Bank', 'Airtel Payments Bank'), ('Paytm Payments Bank', 'Paytm Payments Bank')], max_length=100),
        ),
    ]
