# Generated by Django 4.2.13 on 2026-03-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_payrollbank_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollbank',
            name='IFSC',
            field=models.CharField(max_length=13),
        ),
    ]
