# Generated by Django 4.2.13 on 2026-03-04 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_school_group_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0015_alter_payrollbank_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('payroll_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reconciled_on', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
            ],
            options={
                'unique_together': {('school', 'month', 'year')},
            },
        ),
    ]
