# Generated by Django 4.2.13 on 2026-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_payrollbankreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonthly',
            name='salary_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollmonthly',
            name='total_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollmonthly',
            name='working_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
