# Generated by Django 4.2.13 on 2026-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_payrollmonthly_salary_days_payrollmonthly_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='Sandwich_Leave_Policy',
            field=models.BooleanField(default=False),
        ),
    ]
