# Generated by Django 4.2.13 on 2026-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_payrollsettings_sandwich_leave_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='grace_mins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
