# Generated by Django 4.2.13 on 2026-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiattend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodevices',
            name='BioDeviceId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
