# Generated by Django 5.2.1 on 2025-10-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
        ('setup', '0011_homework_time'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingallocation',
            name='not_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingallocation',
            name='not_last',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReservedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptive_day', models.BooleanField(blank=True, default=False, null=True)),
                ('adaptive_period', models.BooleanField(blank=True, default=False, null=True)),
                ('sch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subjects')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot')),
            ],
        ),
    ]
