# Generated by Django 4.1.3 on 2023-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
