# Generated by Django 4.1.3 on 2024-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
