# Generated by Django 4.1.3 on 2024-12-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notification_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
