# Generated by Django 4.1.3 on 2024-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_school_notification_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='web_aboutus',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='web_admission',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='web_contactus',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='web_gallery',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
