# Generated by Django 4.2.13 on 2026-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_school_web_aboutus_school_web_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='group_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='group_code'),
        ),
    ]
