# Generated by Django 4.2.13 on 2026-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_school_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='group_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
