# Generated by Django 4.2.13 on 2026-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_school_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='regno',
            field=models.CharField(max_length=50),
        ),
    ]
