# Generated by Django 4.2.13 on 2026-06-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_school_regno'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_kmh', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('heading', models.SmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mappls_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_settings', to='institutions.school')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_kmh', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('heading', models.SmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='transport_v_vehicle_8e90d9_idx')],
            },
        ),
    ]
