# Generated by Django 4.2.13 on 2026-06-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0022_alter_students_blood_group_alter_students_email'),
        ('institutions', '0008_alter_school_regno'),
        ('transport', '0002_vehicleposition_gpssettings_vehiclepositionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], default='AM', max_length=2)),
                ('status', models.CharField(choices=[('Boarded', 'Boarded'), ('Absent', 'Absent'), ('Missed', 'Missed Bus')], default='Boarded', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.stop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.students')),
            ],
            options={
                'ordering': ['stop__sequence', 'student__first_name'],
                'unique_together': {('student', 'date', 'trip')},
            },
        ),
    ]
